"use client";
import {useEffect,useState} from "react";
import type {ReactNode} from "react";
import {Activity,BarChart3,Bot,Building2,CheckCircle2,CreditCard,Database,FileText,LayoutDashboard,LogOut,MessageSquare,Settings,ShieldCheck,UserCog,Users,WalletCards} from "lucide-react";
import {ThemeControl,MobileMenu,StatusPill} from "../components";
const nav=[
 {id:"overview",label:"Overview",icon:LayoutDashboard},{id:"accounts",label:"Accounts",icon:Users},{id:"registration",label:"Registration",icon:UserCog},{id:"whatsapp",label:"WhatsApp",icon:MessageSquare},{id:"ai",label:"AI",icon:Bot},{id:"subscriptions",label:"Subscriptions",icon:CreditCard},{id:"payments",label:"Payments",icon:WalletCards},{id:"documents",label:"Invoices & Documents",icon:FileText},{id:"reports",label:"Reports",icon:BarChart3},{id:"backups",label:"Google Sheets / Backup",icon:Database},{id:"audit",label:"Audit Logs",icon:Activity},{id:"security",label:"Security",icon:ShieldCheck},{id:"settings",label:"System Settings",icon:Settings}
];
async function api(path:string,opts:RequestInit={}){const r=await fetch(path,{...opts,cache:"no-store"});const x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||"Request failed");return x}
export default function Admin(){
 const [active,setActive]=useState("overview"),[open,setOpen]=useState(false),[d,setD]=useState<any>({clients:[],stats:{}}),[audit,setAudit]=useState<any[]>([]),[payments,setPayments]=useState<any[]>([]),[wa,setWa]=useState<any>({integrations:[]}),[reports,setReports]=useState<any>({}),[ai,setAi]=useState<any>({}),[plans,setPlans]=useState<any[]>([]),[msg,setMsg]=useState(""),[aiResult,setAiResult]=useState("");
 const [clientForm,setClientForm]=useState({businessName:"",email:"",password:""}),[planForm,setPlanForm]=useState({name:"",amount:"",days:"30"}),[aiPrompt,setAiPrompt]=useState("Summarize the current administration dashboard and identify safe next actions.");
 async function load(){try{const [o,a,p,w,r,ai,s]=await Promise.all([api("/api/admin/overview"),api("/api/admin/audit"),api("/api/admin/payments"),api("/api/admin/whatsapp"),api("/api/admin/reports"),api("/api/admin/ai"),api("/api/admin/subscriptions")]);setD(o);setAudit(a.logs||[]);setPayments(p.payments||[]);setWa(w);setReports(r);setAi(ai);setPlans(s.plans||[])}catch(e:any){location.href="/login?next="+encodeURIComponent(location.pathname)}}
 useEffect(()=>{load()},[]);
 async function act(fn:()=>Promise<any>){try{const x=await fn();setMsg(x.message||"Completed");await load();return x}catch(e:any){setMsg(e.message);return {error:e.message}}}
 async function runAI(){setAiResult("Reading live database metrics…");const x=await act(()=>api("/api/admin/ai/test",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt:aiPrompt})}));setAiResult(x.message||x.error||"")}
 const logout=()=>api("/api/auth/logout",{method:"POST"}).then(()=>location.href="/login");
 return <div className="app-shell"><aside className={`app-sidebar ${open?"mobile-open":""}`}><div className="brand-row"><div className="brand-mark">A</div><div><div className="brand-title">Control Center</div><div className="brand-sub">Enterprise administration</div></div></div><div className="nav-group"><div className="nav-heading">Administration</div>{nav.map(n=>{const I=n.icon;return <button key={n.id} className={`nav-item ${active===n.id?"active":""}`} onClick={()=>{setActive(n.id);setOpen(false)}}><I size={16}/><span>{n.label}</span></button>})}</div><div className="mt-6 border-t border-black/10 pt-4"><ThemeControl/></div></aside>{open&&<div className="mobile-overlay" onClick={()=>setOpen(false)}/>}<div className="app-main"><header className="topbar"><div className="flex items-center gap-3"><MobileMenu open={open} onToggle={()=>setOpen(!open)}/><div><div className="text-xs font-bold uppercase tracking-widest text-blue-700">Administrator</div><h1 className="text-xl font-semibold">{nav.find(x=>x.id===active)?.label}</h1></div></div><div className="topbar-actions"><ThemeControl/><button className="fluent-button" onClick={logout}><LogOut size={15}/> Sign out</button></div></header><main className="content-wrap">{msg&&<div className="notice mb-4">{msg}</div>}
 {active==="overview"&&<><section className="metric-grid">{Object.entries(d.stats||{}).map(([k,v]:any)=><div className="fluent-card metric-card" key={k}><div className="metric-label">{k}</div><div className="metric-value">{String(v)}</div></div>)}</section><section className="grid gap-4 lg:grid-cols-2 mt-5"><Card title="Live administrative AI"><textarea className="fluent-input" rows={4} value={aiPrompt} onChange={e=>setAiPrompt(e.target.value)}/><button className="fluent-primary mt-3" onClick={runAI}><Bot size={15}/> Run live analysis</button><div className="notice mt-3 whitespace-pre-wrap">{aiResult||"AI reads sanitized live MongoDB metrics and recent audit activity. It does not invent infrastructure data or expose secrets."}</div></Card><Card title="Current clients"><ClientTable clients={d.clients||[]} act={act}/></Card></section></>}
 {active==="accounts"&&<section className="grid gap-4 lg:grid-cols-2"><Card title="Create client"><form className="space-y-3" onSubmit={e=>{e.preventDefault();act(()=>api("/api/admin/client",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(clientForm)}))}}><Input label="Business name" value={clientForm.businessName} onChange={v=>setClientForm({...clientForm,businessName:v})}/><Input label="Email" value={clientForm.email} onChange={v=>setClientForm({...clientForm,email:v})}/><Input label="Temporary password (optional)" type="password" value={clientForm.password} onChange={v=>setClientForm({...clientForm,password:v})}/><button className="fluent-primary">Create client</button></form></Card><Card title={`All clients (${d.clients?.length||0})`}><ClientTable clients={d.clients||[]} act={act}/></Card></section>}
 {active==="registration"&&<Card title="Registration control"><div className="notice">Current state: <strong>{d.registrationEnabled===false?"Disabled":"Enabled"}</strong></div><div className="quick-actions mt-4"><button className="fluent-primary" onClick={()=>act(()=>api("/api/admin/registration",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({enabled:true})}))}>Enable registration</button><button className="fluent-button" onClick={()=>act(()=>api("/api/admin/registration",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({enabled:false})}))}>Disable registration</button></div><p className="section-subtitle mt-4">The public registration endpoint and Register UI read this same database setting.</p></Card>}
 {active==="whatsapp"&&<section className="grid gap-4 lg:grid-cols-2"><Card title="Connected WhatsApp accounts"><DataList rows={wa.integrations||[]} empty="No WhatsApp integrations."/><div className="notice mt-4">Webhook events are stored and normalized into messages. Admins can enable or disable automation per client without seeing access tokens.</div></Card><Card title="WhatsApp operations"><div className="activity-list">{["View WABA information","View connected phone numbers","View webhook status","View message activity","Inspect webhook errors","Disable / re-enable automation","View message statistics"].map(x=><div className="activity-row" key={x}><span>{x}</span><StatusPill tone="success">Live data</StatusPill></div>)}</div></Card></section>}
 {active==="ai"&&<section className="grid gap-4 lg:grid-cols-2"><Card title="AI administration"><div className="metric-grid"><Metric title="Configured clients" value={ai.configured||0}/><Metric title="AI usage" value={ai.usage||0}/><Metric title="Failures" value={ai.failures||0}/></div><div className="notice mt-4">Client API keys remain encrypted and are never returned to the administrator interface.</div></Card><Card title="Admin AI"><textarea className="fluent-input" rows={5} value={aiPrompt} onChange={e=>setAiPrompt(e.target.value)}/><button className="fluent-primary mt-3" onClick={runAI}>Analyze live system</button><div className="notice mt-3 whitespace-pre-wrap">{aiResult}</div></Card></section>}
 {active==="subscriptions"&&<section className="grid gap-4 lg:grid-cols-2"><Card title="Create subscription plan"><form className="space-y-3" onSubmit={e=>{e.preventDefault();act(()=>api("/api/admin/plans",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(planForm)}))}}><Input label="Plan name" value={planForm.name} onChange={v=>setPlanForm({...planForm,name:v})}/><Input label="Amount (KES)" type="number" value={planForm.amount} onChange={v=>setPlanForm({...planForm,amount:v})}/><Input label="Duration (days)" type="number" value={planForm.days} onChange={v=>setPlanForm({...planForm,days:v})}/><button className="fluent-primary">Create plan</button></form></Card><Card title="Published plans"><DataList rows={plans} empty="No plans."/></Card></section>}
 {active==="payments"&&<Card title="Payment administration"><div className="activity-list">{payments.slice(0,100).map((p:any)=><div className="activity-row" key={p._id}><div><strong>{p.reference||p.checkoutRequestId||"Payment"}</strong><div className="text-xs text-gray-500">KES {p.amount||0} · {p.createdAt?new Date(p.createdAt).toLocaleString():""}</div></div><div className="quick-actions"><StatusPill tone={p.status==="FAILED"?"danger":p.status==="PAID"||p.status==="VERIFIED"?"success":"warning"}>{p.status}</StatusPill><button className="fluent-button" onClick={()=>act(()=>api("/api/admin/payment/status",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({paymentId:p._id,status:"VERIFIED"})}))}>Verify</button><button className="fluent-button" onClick={()=>act(()=>api("/api/admin/payment/status",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({paymentId:p._id,status:"FAILED"})}))}>Mark failed</button></div></div>)}</div></Card>}
 {active==="documents"&&<Card title="Document administration"><div className="activity-list">{d.clients?.map((c:any)=><div className="activity-row" key={c._id}><div><strong>{c.businessName}</strong><div className="text-xs text-gray-500">{c.documentCount} documents</div></div><button className="fluent-primary" onClick={()=>act(()=>api("/api/admin/client/approve-documents",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({businessId:c._id})}))}>Approve documents</button></div>)}</div></Card>}
 {active==="reports"&&<Card title="Live operational reports"><div className="metric-grid">{Object.entries(reports).map(([k,v]:any)=><Metric key={k} title={k} value={v}/>)}</div><div className="quick-actions mt-5">{["customers","transactions","invoices","subscriptions","audit","messages"].map(k=><a className="fluent-button" key={k} href={`/api/admin/export/${k}`}>Export {k} CSV</a>)}</div></Card>}
 {active==="backups"&&<Card title="Google Sheets backup"><div className="notice">MongoDB remains primary. The configured Google service account and sheet ID are used only server-side. No credentials are exposed to the browser.</div><button className="fluent-primary mt-4" onClick={()=>act(()=>api("/api/admin/backup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"google_sheets"})}))}>Run backup</button></Card>}
 {active==="audit"&&<Card title="Audit logs"><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Target</th><th>Metadata</th></tr></thead><tbody>{audit.map((x:any)=><tr key={x._id}><td>{x.createdAt?new Date(x.createdAt).toLocaleString():""}</td><td>{x.actor}</td><td><strong>{x.action}</strong></td><td>{x.target||"—"}</td><td className="text-xs">{JSON.stringify(x.meta||{})}</td></tr>)}</tbody></table></div></Card>}
 {active==="security"&&<section className="grid gap-4 lg:grid-cols-2"><Card title="Security state"><div className="activity-list">{["MongoDB role authorization","HttpOnly session cookies","Password hashing","Encrypted credentials","OTP/email verification","Audit logging","Login failure tracking","Admin API protection","No secret values in UI"].map(x=><div className="activity-row" key={x}><span>{x}</span><StatusPill tone="success">Enabled</StatusPill></div>)}</div></Card><Card title="Administrator authorization"><div className="notice">The hidden admin URL is not the security boundary. Every administrative API checks the current MongoDB user and requires <strong>role = ADMIN</strong>.</div></Card></section>}
 {active==="settings"&&<section className="grid gap-4 lg:grid-cols-2"><Card title="System controls"><div className="activity-list">{["Registration","WhatsApp webhook","AI model","Daraja environment","SMTP","Google Sheets","Audit logging"].map(x=><div className="activity-row" key={x}><span>{x}</span><StatusPill tone="success">Environment-backed</StatusPill></div>)}</div></Card><Card title="Appearance"><ThemeControl/><div className="notice mt-4">System, Mac and Normal modes are stored in the browser and do not modify environment variables.</div></Card></section>}
 </main></div></div>
}
function Metric({title,value}:{title:string;value:any}){return <div className="fluent-card metric-card"><div className="metric-label">{title}</div><div className="metric-value">{String(value)}</div></div>}
function Card({title,children}:{title:string;children:ReactNode}){return <div className="fluent-card section-card"><div className="section-title">{title}</div>{children}</div>}
function Input({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="block text-sm font-medium">{label}<input className="fluent-input mt-1" type={type} value={value||""} onChange={e=>onChange(e.target.value)}/></label>}
function ClientTable({clients,act}:{clients:any[];act:(f:()=>Promise<any>)=>Promise<any>}){return <div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Business</th><th>Email</th><th>Status</th><th>Role</th><th>Actions</th></tr></thead><tbody>{clients.map(c=><tr key={c._id}><td>{c.businessName}</td><td>{c.email}</td><td><StatusPill tone={c.status==="ACTIVE"?"success":"warning"}>{c.status}</StatusPill></td><td>{c.role}</td><td><div className="quick-actions"><button className="fluent-button" onClick={()=>act(()=>api(`/api/admin/client/${c._id}/status`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:c.status==="SUSPENDED"?"ACTIVE":"SUSPENDED"})}))}>{c.status==="SUSPENDED"?"Reactivate":"Suspend"}</button><button className="fluent-button" onClick={()=>act(()=>api(`/api/admin/client/${c._id}/role`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({role:c.role==="ADMIN"?"CLIENT_OWNER":"ADMIN"})}))}>{c.role==="ADMIN"?"Demote":"Promote"}</button><button className="fluent-button" onClick={()=>act(()=>api(`/api/admin/client/${c._id}/verify-email`,{method:"POST"}))}>Verify</button></div></td></tr>)}</tbody></table></div>}
function DataList({rows,empty}:{rows:any[];empty:string}){return <div className="activity-list mt-3">{rows.slice(0,100).map((x:any,i)=><div className="activity-row" key={x._id||i}><div><strong>{x.businessId||x.reference||x.name||x.plan||x.phoneNumberId||"Record"}</strong><div className="text-xs text-gray-500">{x.createdAt?new Date(x.createdAt).toLocaleString():""}</div></div><StatusPill tone={x.status==="FAILED"?"danger":x.status==="ACTIVE"||x.status==="PAID"?"success":"neutral"}>{x.status||"Recorded"}</StatusPill></div>)}{!rows.length&&<div className="text-sm text-gray-500">{empty}</div>}</div>}
