"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
export default function Register(){
 const [businessName,setBusinessName]=useState(""); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [code,setCode]=useState(""); const [step,setStep]=useState<"register"|"verify">("register"); const [msg,setMsg]=useState(""); const r=useRouter();
 async function register(e:React.FormEvent){e.preventDefault();setMsg("");const x=await fetch("/api/auth/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({businessName,email,password})});const d=await x.json();if(!x.ok){setMsg(d.error||"Registration failed");return}setStep("verify");setMsg("Verification code sent to your email.")}
 async function verify(e:React.FormEvent){e.preventDefault();setMsg("");const x=await fetch("/api/auth/verify-email",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,code})});const d=await x.json();if(!x.ok){setMsg(d.error||"Verification failed");return}r.push("/login?registered=1")}
 return <main className="grid min-h-screen place-items-center p-6"><form onSubmit={step==="register"?register:verify} className="fluent-card w-full max-w-md p-7"><div className="text-xs font-bold uppercase tracking-widest text-blue-700">Client account</div><h1 className="mt-2 text-2xl font-semibold">{step==="register"?"Create your account":"Verify your email"}</h1>{step==="register"?<><div className="mt-6"><label className="fluent-label">Business name</label><input className="fluent-input" value={businessName} onChange={e=>setBusinessName(e.target.value)} required/></div><div className="mt-4"><label className="fluent-label">Email</label><input className="fluent-input" value={email} onChange={e=>setEmail(e.target.value)} type="email" required/></div><div className="mt-4"><label className="fluent-label">Password</label><input className="fluent-input" value={password} onChange={e=>setPassword(e.target.value)} type="password" minLength={12} required/><p className="mt-1 text-xs text-gray-500">At least 12 characters.</p></div><button className="fluent-primary mt-6 w-full">Create account</button></>:<><p className="mt-4 text-sm text-gray-600">Enter the 6-digit code sent to <strong>{email}</strong>.</p><div className="mt-5"><label className="fluent-label">Verification code</label><input className="fluent-input" value={code} onChange={e=>setCode(e.target.value)} inputMode="numeric" maxLength={6} required/></div><button className="fluent-primary mt-6 w-full">Verify email</button></>}{msg&&<div className="mt-4 rounded-md bg-blue-50 p-3 text-sm text-blue-800">{msg}</div>}<button type="button" className="mt-4 w-full text-sm text-blue-700" onClick={()=>r.push("/login")}>Back to sign in</button></form></main>
}

<!-- Project integration marker: complete admin-role + registration build -->
