"use client";
import {useEffect,useState} from "react";
import {CheckCircle2,Download,Loader2,ShieldCheck} from "lucide-react";
export default function VerifyReceipt({params}:{params:Promise<{token:string}>}){
 const [token,setToken]=useState(""),[data,setData]=useState<any>(null),[error,setError]=useState("");
 useEffect(()=>{params.then(({token})=>{setToken(token);fetch(`/api/public/receipts/verify/${token}`,{cache:"no-store"}).then(async r=>{const x=await r.json();if(!r.ok)throw Error(x.error||"Receipt could not be verified");setData(x)}).catch(e=>setError(e.message))})},[params]);
 if(error)return <main className="verify-page"><div className="verify-card"><div className="verify-brand">GEOPRAM TECHNOLOGIES</div><h1>Receipt verification failed</h1><p>{error}</p></div></main>;
 if(!data)return <main className="verify-page"><div className="verify-card"><Loader2 className="spin"/><p>Verifying receipt…</p></div></main>;
 const r=data.receipt;
 return <main className="verify-page"><div className="verify-card"><div className="verify-brand">GEOPRAM TECHNOLOGIES</div><div className="verify-badge"><CheckCircle2 size={18}/> Verified digital receipt</div><h1>{r.number}</h1><p className="verify-sub">This receipt was verified directly against the payment records.</p><div className="verify-grid"><div><span>Business</span><strong>{r.businessName}</strong></div><div><span>Invoice</span><strong>{r.invoiceNumber||"—"}</strong></div><div><span>Amount</span><strong>{r.currency} {Number(r.amount||0).toLocaleString(undefined,{minimumFractionDigits:2})}</strong></div><div><span>Status</span><strong>{r.status}</strong></div><div><span>Payment method</span><strong>{r.method}</strong></div><div><span>M-Pesa receipt</span><strong>{r.mpesaReceiptNumber||"—"}</strong></div><div><span>Paid at</span><strong>{r.paidAt?new Date(r.paidAt).toLocaleString():"—"}</strong></div></div><div className="verify-qr"><img src={`/api/public/receipts/verify/${token}/qr`} alt="Receipt verification QR code"/><div><strong>Scan to verify</strong><p>Anyone can scan this QR code to confirm the receipt online.</p><a className="fluent-button" href={`/api/public/receipts/verify/${token}/pdf`} target="_blank"><Download size={15}/> Open receipt PDF</a></div></div><div className="verify-secure"><ShieldCheck size={17}/> Verification is read-only. Payment credentials and private customer data are not exposed.</div><div className="verify-watermark">G</div></div></main>
}
