"use client";
import {useEffect,useState} from "react";
import {CheckCircle2, CreditCard, Loader2, ShieldCheck} from "lucide-react";
export default function PayInvoice({params}:{params:Promise<{token:string}>}){
 const [invoice,setInvoice]=useState<any>(null),[phone,setPhone]=useState(""),[tokenRef,setTokenRef]=useState(""),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[error,setError]=useState("");
 useEffect(()=>{params.then(({token})=>{setTokenRef(token);return fetch(`/api/public/invoices/${token}`,{cache:"no-store"}).then(async r=>{const x=await r.json();if(!r.ok)throw Error(x.error||"Invoice unavailable");setInvoice(x.invoice)}).catch(e=>setError(e.message))})},[params]);
 async function pay(){setBusy(true);setMsg("");setError("");try{const r=await fetch(`/api/public/invoices/${tokenRef}/pay`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({phone,method:"M-Pesa STK"})});const x=await r.json();if(!r.ok)throw Error(x.error||"Payment could not start");setMsg(x.message||"Check your phone for the M-Pesa prompt.");}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 if(error&&!invoice)return <main className="public-pay"><div className="pay-card"><div className="pay-brand">Fluent Business Automation</div><h1>Payment link unavailable</h1><p>{error}</p></div></main>;
 if(!invoice)return <main className="public-pay"><div className="pay-card"><Loader2 className="spin"/><p>Loading invoice…</p></div></main>;
 const paid=invoice.status==="PAID";
 return <main className="public-pay"><div className="pay-card"><div className="pay-brand">{invoice.businessName}</div><div className="pay-head"><div><p className="eyebrow">SECURE INVOICE</p><h1>{invoice.title}</h1><p>Invoice {invoice.number}</p></div><div className="pay-amount">{invoice.currency} {Number(invoice.amount).toLocaleString(undefined,{minimumFractionDigits:2})}</div></div>{invoice.description&&<p className="pay-description">{invoice.description}</p>}{paid?<div className="pay-success"><CheckCircle2/> This invoice has already been paid.</div>:<><label>Kenyan M-Pesa number<input className="pay-input" placeholder="07XXXXXXXX" value={phone} onChange={e=>setPhone(e.target.value)}/></label><button className="pay-button" onClick={pay} disabled={busy}>{busy?<><Loader2 className="spin"/> Starting payment…</>:<><CreditCard/> Pay with M-Pesa</>}</button>{msg&&<div className="pay-success"><CheckCircle2/>{msg}</div>}{error&&<div className="pay-error">{error}</div>}<div className="pay-secure"><ShieldCheck/> Secure payment request · Your payment is confirmed by the payment callback before the invoice is marked paid.</div></>}</div></main>
}
