"use client";
import {useEffect,useState} from "react";
import {Bot,CheckCircle2,ChevronRight,FileText,LayoutDashboard,LogOut,MessageSquare,Users,WalletCards,ReceiptText,Settings,ShieldCheck,Activity,CreditCard,Tags,Upload,Download,Clock3, Zap, Smartphone, Search} from "lucide-react";
import {ThemeControl,MobileMenu,StatusPill} from "../components";

const sections=[
 {id:"overview",label:"Overview",icon:LayoutDashboard},
 {id:"whatsapp",label:"WhatsApp",icon:MessageSquare,items:["Connection","Conversations","Messages","Automation"]},
 {id:"customers",label:"Customers",icon:Users,items:["Customers","Groups","Tags"]},
 {id:"ai",label:"AI",icon:Bot,items:["Configuration","Knowledge","Usage"]},
 {id:"payments",label:"Payments",icon:WalletCards,items:["M-Pesa","Transactions"]},
 {id:"subscriptions",label:"Subscriptions",icon:CreditCard},
 {id:"documents",label:"Invoices & Receipts",icon:ReceiptText},
 {id:"reports",label:"Reports",icon:FileText},
 {id:"settings",label:"Settings",icon:Settings},
 {id:"activity",label:"Account activity",icon:Activity},
];

function Nav({active,setActive}:{active:string;setActive:(x:string)=>void}){return <>
 <div className="nav-group"><div className="nav-heading">Workspace</div>{sections.map(s=>{const I=s.icon;return <button key={s.id} className={`nav-item ${active===s.id?"active":""}`} onClick={()=>setActive(s.id)}><I size={16}/><span>{s.label}</span><ChevronRight size={14} className="ml-auto opacity-40"/></button>})}</div>
 <div className="nav-group"><div className="nav-heading">Account</div><button className="nav-item" onClick={()=>document.getElementById("profile")?.scrollIntoView({behavior:"smooth"})}><ShieldCheck size={16}/>Profile</button></div>
 </>}

export default function Dashboard(){
 const [active,setActive]=useState("overview"); const [open,setOpen]=useState(false); const [profile,setProfile]=useState<any>(null); const [activity,setActivity]=useState<any[]>([]); const [wa,setWa]=useState<any>(null); const [ai,setAi]=useState<any>(null); const [msg,setMsg]=useState(""); const [waForm,setWaForm]=useState({wabaId:"",phoneNumberId:"",accessToken:"",automationEnabled:true}); const [aiForm,setAiForm]=useState({apiKey:"",model:"gpt-5.6-luna",systemInstructions:"",responseTone:"Professional",responseLength:"Balanced",enabled:true});
 useEffect(()=>{Promise.all([fetch("/api/client/profile"),fetch("/api/client/activity"),fetch("/api/client/whatsapp"),fetch("/api/client/ai")]).then(async rs=>{if(rs[0].status===401){location.href="/login";return}const [p,a,w,i]=await Promise.all(rs.map(r=>r.json()));setProfile(p.profile);setActivity(a.activity||[]);setWa(w);setAi(i)}).catch(()=>setMsg("Unable to load account modules."))},[]);
 async function saveWa(e:any){e.preventDefault();const r=await fetch("/api/client/whatsapp",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(waForm)});const x=await r.json();setMsg(x.message||x.error||"Saved");if(r.ok)setWa({...wa,connected:true,phoneNumberId:waForm.phoneNumberId,automationEnabled:waForm.automationEnabled})}
 async function saveAi(e:any){e.preventDefault();const r=await fetch("/api/client/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(aiForm)});const x=await r.json();setMsg(x.message||x.error||"Saved");if(r.ok)setAi({...ai,configured:true,enabled:aiForm.enabled,model:aiForm.model})}
 const logout=()=>fetch("/api/auth/logout",{method:"POST"}).then(()=>location.href="/login");
 return <div className="app-shell"><aside className={`app-sidebar ${open?"mobile-open":""}`}><div className="brand-row"><div className="brand-mark">G</div><div><div className="brand-title">GeoPram Automation</div><div className="brand-sub">Client workspace</div></div></div><Nav active={active} setActive={x=>{setActive(x);setOpen(false)}}/><div className="mt-6 border-t border-black/10 pt-4"><ThemeControl/></div></aside>{open&&<div className="mobile-overlay" onClick={()=>setOpen(false)}/>}<div className="app-main"><header className="topbar"><div className="flex items-center gap-3"><MobileMenu open={open} onToggle={()=>setOpen(!open)}/><div><div className="text-xs font-bold uppercase tracking-widest text-blue-700">Client workspace</div><h1 className="text-xl font-semibold">{sections.find(x=>x.id===active)?.label||"Dashboard"}</h1></div></div><div className="topbar-actions"><ThemeControl/><button className="fluent-button" onClick={logout}><LogOut size={15} className="mr-1 inline"/>Sign out</button></div></header><main className="content-wrap">
 {msg&&<div className="mb-4 notice">{msg}</div>}
 <section className="metric-grid"><div className="fluent-card metric-card"><div className="metric-label">Automation</div><div className="metric-value">{wa?.automationEnabled?"Active":"Off"}</div></div><div className="fluent-card metric-card"><div className="metric-label">Subscription</div><div className="metric-value text-base">{profile?.subscription?.plan||"Not subscribed"}</div></div><div className="fluent-card metric-card"><div className="metric-label">AI</div><div className="metric-value text-base">{ai?.enabled?"Enabled":"Not configured"}</div></div><div className="fluent-card metric-card"><div className="metric-label">Account</div><div className="metric-value text-base">{profile?.status||"Loading"}</div></div></section>
 <section className="mt-5 fluent-card section-card"><div className="flex items-start justify-between gap-4"><div><div className="section-title">Business workspace</div><div className="section-subtitle">{profile?.businessName||"Loading business profile"} · {profile?.email||""}</div></div><StatusPill tone={profile?.status==="ACTIVE"?"success":"warning"}>{profile?.status||"PENDING"}</StatusPill></div></section>
 {active==="overview"&&<><section className="mt-5"><div className="section-title mb-3">Quick actions</div><div className="menu-grid">{[[MessageSquare,"Connect WhatsApp","Link your WhatsApp Business number.","whatsapp"],[Users,"Add customer","Create and organize a CRM contact.","customers"],[Bot,"Configure AI","Securely configure client AI.","ai"],[WalletCards,"Record payment","Track M-Pesa and transaction records.","payments"],[FileText,"Create document","Invoices, receipts and approvals.","documents"],[Activity,"Review activity","See your account audit history.","activity"]].map(([I,t,p,id]:any)=><button key={id} className="fluent-card menu-card" onClick={()=>setActive(id)}><div className="menu-icon"><I size={17}/></div><h3>{t}</h3><p>{p}</p></button>)}</div></section><section id="profile" className="mt-5 grid gap-4 lg:grid-cols-2"><div className="fluent-card section-card"><div className="section-title">Account profile</div><div className="activity-list mt-3"><div className="activity-row"><span>Email</span><strong>{profile?.email||"—"}</strong></div><div className="activity-row"><span>Email verification</span><StatusPill tone={profile?.emailVerified?"success":"warning"}>{profile?.emailVerified?"Verified":"Pending"}</StatusPill></div><div className="activity-row"><span>Subscription</span><span>{profile?.subscription?.plan||"None"}</span></div></div></div><div className="fluent-card section-card"><div className="section-title">Recent activity</div><div className="activity-list mt-3">{activity.slice(0,5).map((x:any)=><div className="activity-row" key={x.createdAt+x.action}><div><strong className="text-sm">{x.action}</strong><div className="text-xs text-gray-500">{x.createdAt?new Date(x.createdAt).toLocaleString():""}</div></div><CheckCircle2 size={16} className="text-green-600"/></div>)}{!activity.length&&<div className="text-sm text-gray-500">No account activity yet.</div>}</div></div></section></>}
 {active==="whatsapp"&&<section className="mt-5 grid gap-4 lg:grid-cols-2"><div className="fluent-card section-card"><div className="section-title">WhatsApp Business connection</div><div className="section-subtitle">Credentials are encrypted before storage. Secrets are never displayed after saving.</div><div className="mt-4 space-y-3"><div className="notice">Connection: <strong>{wa?.connected?"Connected":"Not connected"}</strong> · Webhook: <strong>{wa?.webhookVerified?"Verified":"Pending"}</strong></div><form onSubmit={saveWa} className="space-y-3"><input className="fluent-input" placeholder="WABA ID" value={waForm.wabaId} onChange={e=>setWaForm({...waForm,wabaId:e.target.value})}/><input className="fluent-input" placeholder="Phone Number ID" value={waForm.phoneNumberId} onChange={e=>setWaForm({...waForm,phoneNumberId:e.target.value})}/><input className="fluent-input" type="password" placeholder="WhatsApp access token" value={waForm.accessToken} onChange={e=>setWaForm({...waForm,accessToken:e.target.value})}/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={waForm.automationEnabled} onChange={e=>setWaForm({...waForm,automationEnabled:e.target.checked})}/> Enable automation</label><button className="fluent-primary" type="submit">Save secure connection</button></form></div></div><div className="fluent-card section-card"><div className="section-title">Automation activities</div><div className="activity-list mt-3">{["Welcome messages","Away messages","Business-hours responses","Keyword triggers","Customer journeys","Conversation history","Message status tracking"].map(x=><div className="activity-row" key={x}><span>{x}</span><StatusPill tone="warning">Configure</StatusPill></div>)}</div></div></section>}
 {active==="customers"&&<section className="mt-5 grid gap-4 lg:grid-cols-2"><div className="fluent-card section-card"><div className="section-title">Customer / CRM</div><div className="quick-actions mt-4"><button className="fluent-primary">Create customer</button><button className="fluent-button"><Upload size={14} className="inline mr-1"/>Import</button><button className="fluent-button"><Download size={14} className="inline mr-1"/>Export</button></div><div className="mt-4"><input className="fluent-input" placeholder="Search customers"/><div className="notice mt-3"><Search size={14} className="inline mr-1"/>Customer records, groups, tags, notes and conversation history are managed from this workspace.</div></div></div><div className="fluent-card section-card"><div className="section-title">Segmentation</div><div className="activity-list mt-3">{["Customer groups","Tags","Interaction history","Conversation history","Bulk messaging"].map(x=><div className="activity-row" key={x}><span>{x}</span><StatusPill tone="warning">Configure</StatusPill></div>)}</div></div></section>}
 {active==="ai"&&<section className="mt-5 grid gap-4 lg:grid-cols-2"><div className="fluent-card section-card"><div className="section-title">Client AI configuration</div><div className="section-subtitle">Your API key is encrypted at rest and is never rendered back to the browser.</div><form onSubmit={saveAi} className="mt-4 space-y-3"><input className="fluent-input" type="password" placeholder="OpenAI API key" value={aiForm.apiKey} onChange={e=>setAiForm({...aiForm,apiKey:e.target.value})}/><select className="fluent-input" value={aiForm.model} onChange={e=>setAiForm({...aiForm,model:e.target.value})}><option>gpt-5.6-luna</option><option>gpt-5.6-sol</option></select><textarea className="fluent-input" rows={4} placeholder="System instructions / business knowledge" value={aiForm.systemInstructions} onChange={e=>setAiForm({...aiForm,systemInstructions:e.target.value})}/><div className="grid grid-cols-2 gap-3"><select className="fluent-input" value={aiForm.responseTone} onChange={e=>setAiForm({...aiForm,responseTone:e.target.value})}><option>Professional</option><option>Friendly</option><option>Concise</option></select><select className="fluent-input" value={aiForm.responseLength} onChange={e=>setAiForm({...aiForm,responseLength:e.target.value})}><option>Balanced</option><option>Short</option><option>Detailed</option></select></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={aiForm.enabled} onChange={e=>setAiForm({...aiForm,enabled:e.target.checked})}/> Enable AI replies</label><button className="fluent-primary">Save AI configuration</button></form></div><div className="fluent-card section-card"><div className="section-title">AI activities</div><div className="activity-list mt-3">{["Generate customer responses","Summarize conversations","Extract customer information","Classify customer requests","Human escalation","Usage monitoring","Error monitoring"].map(x=><div className="activity-row" key={x}><span>{x}</span><StatusPill tone={ai?.configured?"success":"warning"}>{ai?.configured?"Available":"Configure AI"}</StatusPill></div>)}</div></div></section>}
 {active==="payments"&&<section className="mt-5 grid gap-4 lg:grid-cols-2"><div className="fluent-card section-card"><div className="section-title">M-Pesa / Daraja</div><div className="section-subtitle">Payment credentials remain server-side. No secrets are shown in this workspace.</div><div className="activity-list mt-4">{["Till Number","Shortcode","Callback URL","Initiate payment","Verify callback","Transaction matching","Payment receipts"].map(x=><div className="activity-row" key={x}><span>{x}</span><StatusPill tone="warning">Server setup</StatusPill></div>)}</div></div><div className="fluent-card section-card"><div className="section-title">Transactions</div><div className="notice mt-3">Transaction search, customer matching, invoice matching, pending/failed handling and exports are represented here and can be connected to the configured Daraja environment.</div></div></section>}
 {active==="subscriptions"&&<section className="mt-5 fluent-card section-card"><div className="section-title">Subscriptions</div><div className="menu-grid mt-4">{["Available plans","Subscribe","Change plan","Renew","Cancel","Usage limits","WhatsApp usage","AI usage","Payment status","Subscription invoice","Receipt"].map(x=><div className="fluent-card menu-card" key={x}><div className="menu-icon"><CreditCard size={16}/></div><h3>{x}</h3><p>Client subscription activity.</p></div>)}</div></section>}
 {active==="documents"&&<section className="mt-5 fluent-card section-card"><div className="section-title">Invoices, receipts & documents</div><div className="menu-grid mt-4">{["Create invoice","Edit invoice","View invoice","Download invoice","Email invoice","Mark paid","Generate receipt","Download receipt","Email receipt","Approved documents","Document history"].map(x=><div className="fluent-card menu-card" key={x}><div className="menu-icon"><FileText size={16}/></div><h3>{x}</h3><p>Document workflow and approval activity.</p></div>)}</div></section>}
 {active==="reports"&&<section className="mt-5 fluent-card section-card"><div className="section-title">Reports & exports</div><div className="menu-grid mt-4">{["Customers","Transactions","Invoices","Subscriptions","Activity logs","WhatsApp activity","AI usage","Daily report","Weekly report","Monthly report","Google Sheets backup"].map(x=><div className="fluent-card menu-card" key={x}><div className="menu-icon"><FileText size={16}/></div><h3>{x}</h3><p>Operational report and export.</p></div>)}</div></section>}
 {active==="settings"&&<section className="mt-5 grid gap-4 lg:grid-cols-2"><div className="fluent-card section-card"><div className="section-title">Account settings</div><div className="activity-list mt-3">{["Change password","Reset password","Business information","Account status","Email verification","Secure sessions"].map(x=><div className="activity-row" key={x}><span>{x}</span><button className="fluent-button">Manage</button></div>)}</div></div><div className="fluent-card section-card"><div className="section-title">Appearance</div><p className="section-subtitle">System follows your device preference. Mac gives the workspace a macOS-style surface. Normal uses the standard Fluent enterprise appearance.</p><div className="mt-4"><ThemeControl/></div></div></section>}
 {active==="activity"&&<section className="mt-5 fluent-card section-card"><div className="section-title">Account audit history</div><div className="activity-list mt-4">{activity.map((x:any)=><div className="activity-row" key={x.createdAt+x.action}><div><strong>{x.action}</strong><div className="text-xs text-gray-500">{x.createdAt?new Date(x.createdAt).toLocaleString():""} {x.target?` · ${x.target}`:""}</div></div><StatusPill tone="success">Recorded</StatusPill></div>)}{!activity.length&&<div className="text-sm text-gray-500">No activity recorded.</div>}</div></section>}
 </main></div></div>
}
